CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);

CREATE TABLE SPIELTAG (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  start_date_time TIMESTAMP NOT NULL
);

CREATE TABLE PLAYER_SUBMIT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  player_name VARCHAR(250) NOT NULL,
  user_name VARCHAR(250) NOT NULL,
  spieltag VARCHAR(250) NOT NULL,
  saison VARCHAR(250) NOT NULL,
  punkte INT
);


