CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  mail_address VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);

CREATE TABLE PLAYER_SUBMIT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  player_name VARCHAR(250) NOT NULL,
  user_name VARCHAR(250) NOT NULL,
  spieltag VARCHAR(250) NOT NULL,
  saison VARCHAR(250) NOT NULL,
  punkte INT
);

CREATE TABLE SPIELTAG (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);
